-- ═══════════════════════════════════════════════════════════════════════════════
-- ProITBridge Enterprise AI Knowledge Assistant
-- Supabase PostgreSQL Schema Migration
-- ═══════════════════════════════════════════════════════════════════════════════
--
-- Run this entire script in the Supabase SQL Editor:
--   Dashboard → SQL Editor → New Query → Paste → Run
--
-- This migration is IDEMPOTENT — safe to run multiple times.
--
-- Tables created:
--   1. documents         — uploaded document metadata
--   2. chat_history      — persistent conversation records
--   3. analytics_events  — platform telemetry & metrics
--
-- ═══════════════════════════════════════════════════════════════════════════════


-- ─────────────────────────────────────────────────────────────────────────────
-- 1. DOCUMENTS TABLE
-- ─────────────────────────────────────────────────────────────────────────────
-- Stores metadata for every uploaded document.
-- Vector data lives in Pinecone; this table holds the relational metadata
-- and links to Pinecone via document_id embedded in vector metadata.
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS documents (
    -- Primary key: UUID generated by the backend
    id              UUID            DEFAULT gen_random_uuid()    PRIMARY KEY,

    -- Document identity
    name            TEXT            NOT NULL,                               -- Original filename (e.g. "Engineering_Handbook.pdf")
    file_type       TEXT            NOT NULL,                               -- Extension: .pdf, .docx, .txt, .md

    -- Size & chunking
    size_bytes      BIGINT          NOT NULL        DEFAULT 0,              -- Raw file size in bytes
    chunk_count     INTEGER         NOT NULL        DEFAULT 0,              -- Number of chunks indexed in Pinecone

    -- Processing lifecycle
    -- Allowed values: 'queued' → 'processing' → 'indexed' | 'error'
    status          TEXT            NOT NULL        DEFAULT 'queued'
                    CHECK (status IN ('queued', 'processing', 'indexed', 'error')),

    -- Timestamps
    uploaded_at     TIMESTAMPTZ     NOT NULL        DEFAULT now(),
    updated_at      TIMESTAMPTZ     NOT NULL        DEFAULT now()
);

-- Comments
COMMENT ON TABLE  documents               IS 'Metadata registry for all uploaded knowledge base documents';
COMMENT ON COLUMN documents.id            IS 'UUID primary key, also used as document_id in Pinecone vector metadata';
COMMENT ON COLUMN documents.name          IS 'Original filename including extension';
COMMENT ON COLUMN documents.file_type     IS 'File extension (.pdf, .docx, .txt, .md)';
COMMENT ON COLUMN documents.size_bytes    IS 'Raw upload file size in bytes';
COMMENT ON COLUMN documents.chunk_count   IS 'Number of text chunks indexed in Pinecone for this document';
COMMENT ON COLUMN documents.status        IS 'Ingestion lifecycle: queued → processing → indexed | error';
COMMENT ON COLUMN documents.uploaded_at   IS 'Timestamp when the document was first uploaded';
COMMENT ON COLUMN documents.updated_at    IS 'Timestamp of the last status or metadata update';


-- ─────────────────────────────────────────────────────────────────────────────
-- 2. CHAT HISTORY TABLE
-- ─────────────────────────────────────────────────────────────────────────────
-- Persists every user query and AI response for session continuity,
-- analytics, and audit trails.
--
-- Each row is a single message (either user or assistant).
-- A session_id groups related messages into a conversation thread.
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS chat_history (
    -- Primary key
    id                      UUID        DEFAULT gen_random_uuid()    PRIMARY KEY,

    -- Session grouping
    session_id              TEXT        NOT NULL,                               -- Groups messages into a conversation thread

    -- Message content
    role                    TEXT        NOT NULL
                            CHECK (role IN ('user', 'assistant')),              -- Who sent the message
    content                 TEXT        NOT NULL,                               -- Full message text

    -- AI response metadata (NULL for user messages)
    citations               JSONB       NOT NULL    DEFAULT '[]'::jsonb,        -- Array of citation objects
    -- Citation object shape:
    -- {
    --   "doc": "Engineering Handbook.pdf",
    --   "page": 34,
    --   "chunk": "Auth Requirements §4.2",
    --   "score": 0.97
    -- }

    tokens_used             INTEGER     NOT NULL    DEFAULT 0,                  -- Total tokens consumed by this response
    retrieval_latency_ms    REAL,                                               -- Pinecone retrieval time (ms)
    generation_latency_ms   REAL,                                               -- Gemini generation time (ms)

    -- Timestamps
    created_at              TIMESTAMPTZ NOT NULL    DEFAULT now()
);

-- Comments
COMMENT ON TABLE  chat_history                          IS 'Persistent chat message log with citations and performance metrics';
COMMENT ON COLUMN chat_history.session_id               IS 'Conversation thread identifier (UUID or custom string)';
COMMENT ON COLUMN chat_history.role                     IS 'Message author: user or assistant';
COMMENT ON COLUMN chat_history.content                  IS 'Full message text (user query or AI response)';
COMMENT ON COLUMN chat_history.citations                IS 'JSONB array of source citations (doc, page, chunk, score)';
COMMENT ON COLUMN chat_history.tokens_used              IS 'LLM tokens consumed for this response (0 for user messages)';
COMMENT ON COLUMN chat_history.retrieval_latency_ms     IS 'Pinecone vector search latency in milliseconds';
COMMENT ON COLUMN chat_history.generation_latency_ms    IS 'Gemini response generation latency in milliseconds';


-- ─────────────────────────────────────────────────────────────────────────────
-- 3. ANALYTICS EVENTS TABLE
-- ─────────────────────────────────────────────────────────────────────────────
-- Generic event log for platform telemetry.
-- Each event has a type and a flexible JSONB metadata payload.
--
-- Event types used by the backend:
--
--   "document_ingested"  → metadata: {
--       document_id, document_name, chunk_count, processing_time_ms
--   }
--
--   "query_executed"     → metadata: {
--       session_id, latency_ms, retrieval_latency_ms,
--       generation_latency_ms, tokens_used, citation_count,
--       cited_documents: ["file1.pdf", "file2.md"]
--   }
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS analytics_events (
    -- Primary key
    id              UUID            DEFAULT gen_random_uuid()    PRIMARY KEY,

    -- Event classification
    event_type      TEXT            NOT NULL,                                   -- e.g. 'document_ingested', 'query_executed'

    -- Flexible payload
    metadata        JSONB           NOT NULL    DEFAULT '{}'::jsonb,            -- Event-specific data

    -- Timestamps
    created_at      TIMESTAMPTZ     NOT NULL    DEFAULT now()
);

-- Comments
COMMENT ON TABLE  analytics_events              IS 'Platform telemetry and metrics event log';
COMMENT ON COLUMN analytics_events.event_type   IS 'Event category: document_ingested, query_executed, etc.';
COMMENT ON COLUMN analytics_events.metadata     IS 'JSONB payload with event-specific metrics and identifiers';


-- ═══════════════════════════════════════════════════════════════════════════════
-- INDEXES
-- ═══════════════════════════════════════════════════════════════════════════════
-- Performance indexes for the query patterns used by the backend services.

-- documents: filter by processing status (document_service.py)
CREATE INDEX IF NOT EXISTS idx_documents_status
    ON documents (status);

-- documents: sort by upload date (document_service.list_documents)
CREATE INDEX IF NOT EXISTS idx_documents_uploaded_at
    ON documents (uploaded_at DESC);

-- chat_history: load session messages (query_service._load_recent_history)
CREATE INDEX IF NOT EXISTS idx_chat_history_session
    ON chat_history (session_id, created_at DESC);

-- chat_history: filter by role for session listing (history_service.get_all_sessions)
CREATE INDEX IF NOT EXISTS idx_chat_history_role
    ON chat_history (role, created_at DESC);

-- analytics_events: filter by event type (analytics_service.get_analytics)
CREATE INDEX IF NOT EXISTS idx_analytics_event_type
    ON analytics_events (event_type);

-- analytics_events: time-range queries for daily stats (analytics_service._get_daily_query_stats)
CREATE INDEX IF NOT EXISTS idx_analytics_created_at
    ON analytics_events (event_type, created_at DESC);


-- ═══════════════════════════════════════════════════════════════════════════════
-- AUTO-UPDATE TRIGGER FOR documents.updated_at
-- ═══════════════════════════════════════════════════════════════════════════════
-- Automatically sets updated_at to now() on every UPDATE, so the backend
-- doesn't have to explicitly set it (though it does as a safety measure).

CREATE OR REPLACE FUNCTION trigger_set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Drop existing trigger if present (idempotent)
DROP TRIGGER IF EXISTS set_documents_updated_at ON documents;

CREATE TRIGGER set_documents_updated_at
    BEFORE UPDATE ON documents
    FOR EACH ROW
    EXECUTE FUNCTION trigger_set_updated_at();


-- ═══════════════════════════════════════════════════════════════════════════════
-- ROW LEVEL SECURITY (RLS) POLICIES
-- ═══════════════════════════════════════════════════════════════════════════════
-- Enable RLS on all tables but allow full access via the service_role key.
-- The backend connects using SUPABASE_KEY (service_role), so these policies
-- grant unrestricted access while keeping RLS enabled for security posture.

ALTER TABLE documents        ENABLE ROW LEVEL SECURITY;
ALTER TABLE chat_history     ENABLE ROW LEVEL SECURITY;
ALTER TABLE analytics_events ENABLE ROW LEVEL SECURITY;

-- Service-role bypass policies (the backend authenticates with service_role)
DROP POLICY IF EXISTS "service_role_documents" ON documents;
CREATE POLICY "service_role_documents" ON documents FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "service_role_chat_history" ON chat_history;
CREATE POLICY "service_role_chat_history" ON chat_history FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "service_role_analytics_events" ON analytics_events;
CREATE POLICY "service_role_analytics_events" ON analytics_events FOR ALL USING (true) WITH CHECK (true);


-- ═══════════════════════════════════════════════════════════════════════════════
-- PINECONE VECTOR METADATA REFERENCE
-- ═══════════════════════════════════════════════════════════════════════════════
-- Each vector stored in Pinecone carries the following metadata fields.
-- This is NOT a Supabase table — it documents the Pinecone metadata schema
-- so the relationship between PostgreSQL and Pinecone is explicit.
--
-- Pinecone Vector ID format:  {document_id}::chunk::{chunk_index}
--
-- Pinecone Vector Metadata:
-- ┌─────────────────┬─────────┬─────────────────────────────────────────────┐
-- │ Field           │ Type    │ Description                                 │
-- ├─────────────────┼─────────┼─────────────────────────────────────────────┤
-- │ document_id     │ string  │ FK → documents.id (UUID)                    │
-- │ document_name   │ string  │ Original filename                           │
-- │ page_number     │ int     │ Source page (null for non-PDF)               │
-- │ chunk_index     │ int     │ Zero-based chunk position in document       │
-- │ uploaded_at     │ string  │ ISO 8601 timestamp of ingestion             │
-- │ text            │ string  │ Full chunk text (for retrieval display)      │
-- └─────────────────┴─────────┴─────────────────────────────────────────────┘
--
-- Pinecone Index Configuration:
--   Name:      enterprise-rag
--   Dimension: 384
--   Metric:    cosine
--   Type:      Serverless (AWS us-east-1)
--
-- The document_id field in Pinecone metadata links back to documents.id,
-- enabling cascade deletes: when a document is removed, the backend
-- deletes Pinecone vectors filtered by document_id.


-- ═══════════════════════════════════════════════════════════════════════════════
-- VERIFICATION QUERY
-- ═══════════════════════════════════════════════════════════════════════════════
-- Run this after the migration to confirm all tables and indexes exist.

DO $$
DECLARE
    tbl TEXT;
    idx TEXT;
BEGIN
    -- Verify tables
    FOR tbl IN SELECT unnest(ARRAY['documents', 'chat_history', 'analytics_events'])
    LOOP
        IF NOT EXISTS (
            SELECT 1 FROM information_schema.tables
            WHERE table_schema = 'public' AND table_name = tbl
        ) THEN
            RAISE EXCEPTION 'Table "%" does not exist', tbl;
        END IF;
    END LOOP;

    -- Verify indexes
    FOR idx IN SELECT unnest(ARRAY[
        'idx_documents_status',
        'idx_documents_uploaded_at',
        'idx_chat_history_session',
        'idx_chat_history_role',
        'idx_analytics_event_type',
        'idx_analytics_created_at'
    ])
    LOOP
        IF NOT EXISTS (
            SELECT 1 FROM pg_indexes
            WHERE schemaname = 'public' AND indexname = idx
        ) THEN
            RAISE EXCEPTION 'Index "%" does not exist', idx;
        END IF;
    END LOOP;

    RAISE NOTICE '✓ Migration verified — all 3 tables and 6 indexes exist';
END;
$$;
